### PR TITLE
Remove seeds created directly through the controllers

### PR DESCRIPTION
**Pull request by lostie**
⚠️ **Unless there's a strong reason for this to be kept.**

### CODE REVIEW

**Review by dan-palmer — COMMENTED** [review]
This is fine. User research et al aware this is being removed?

**Comment by lostie** [comment]
> This is fine. User research et al aware this is being removed?

Ehrggg, not really. It shouldn't really matter, if for demo purposes, seeds are needed, they should be created some other way (that's my opinion anyway).

**Comment by dan-palmer** [comment]
@lostie Just need to let everybody know that you're removing it and we will be seeding data differently in the future.

I agree that there are nicer ways of doing this.

**Review by dan-palmer — APPROVED** [review]

**Comment by lostie** [comment]
Will be addressed in https://github.com/ministryofjustice/moving-people-safely/pull/212

**Pull request closed without merging**
